// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: CalendarService.proto

package pb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateEventReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *Event                 `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEventReq) Reset() {
	*x = CreateEventReq{}
	mi := &file_CalendarService_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEventReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEventReq) ProtoMessage() {}

func (x *CreateEventReq) ProtoReflect() protoreflect.Message {
	mi := &file_CalendarService_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEventReq.ProtoReflect.Descriptor instead.
func (*CreateEventReq) Descriptor() ([]byte, []int) {
	return file_CalendarService_proto_rawDescGZIP(), []int{0}
}

func (x *CreateEventReq) GetEvent() *Event {
	if x != nil {
		return x.Event
	}
	return nil
}

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Description   string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	TimeBefore    int64                  `protobuf:"varint,7,opt,name=time_before,json=timeBefore,proto3" json:"time_before,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_CalendarService_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_CalendarService_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_CalendarService_proto_rawDescGZIP(), []int{1}
}

func (x *Event) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Event) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Event) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Event) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *Event) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *Event) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Event) GetTimeBefore() int64 {
	if x != nil {
		return x.TimeBefore
	}
	return 0
}

type UpdateEventReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Event         *Event                 `protobuf:"bytes,2,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEventReq) Reset() {
	*x = UpdateEventReq{}
	mi := &file_CalendarService_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEventReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEventReq) ProtoMessage() {}

func (x *UpdateEventReq) ProtoReflect() protoreflect.Message {
	mi := &file_CalendarService_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEventReq.ProtoReflect.Descriptor instead.
func (*UpdateEventReq) Descriptor() ([]byte, []int) {
	return file_CalendarService_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateEventReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateEventReq) GetEvent() *Event {
	if x != nil {
		return x.Event
	}
	return nil
}

type DeleteEventReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEventReq) Reset() {
	*x = DeleteEventReq{}
	mi := &file_CalendarService_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEventReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEventReq) ProtoMessage() {}

func (x *DeleteEventReq) ProtoReflect() protoreflect.Message {
	mi := &file_CalendarService_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEventReq.ProtoReflect.Descriptor instead.
func (*DeleteEventReq) Descriptor() ([]byte, []int) {
	return file_CalendarService_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteEventReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetEventsDayReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Start         *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventsDayReq) Reset() {
	*x = GetEventsDayReq{}
	mi := &file_CalendarService_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventsDayReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventsDayReq) ProtoMessage() {}

func (x *GetEventsDayReq) ProtoReflect() protoreflect.Message {
	mi := &file_CalendarService_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventsDayReq.ProtoReflect.Descriptor instead.
func (*GetEventsDayReq) Descriptor() ([]byte, []int) {
	return file_CalendarService_proto_rawDescGZIP(), []int{4}
}

func (x *GetEventsDayReq) GetStart() *timestamppb.Timestamp {
	if x != nil {
		return x.Start
	}
	return nil
}

type GetEventsDayResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*Event               `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventsDayResp) Reset() {
	*x = GetEventsDayResp{}
	mi := &file_CalendarService_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventsDayResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventsDayResp) ProtoMessage() {}

func (x *GetEventsDayResp) ProtoReflect() protoreflect.Message {
	mi := &file_CalendarService_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventsDayResp.ProtoReflect.Descriptor instead.
func (*GetEventsDayResp) Descriptor() ([]byte, []int) {
	return file_CalendarService_proto_rawDescGZIP(), []int{5}
}

func (x *GetEventsDayResp) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

type GetEventsWeekReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Start         *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventsWeekReq) Reset() {
	*x = GetEventsWeekReq{}
	mi := &file_CalendarService_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventsWeekReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventsWeekReq) ProtoMessage() {}

func (x *GetEventsWeekReq) ProtoReflect() protoreflect.Message {
	mi := &file_CalendarService_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventsWeekReq.ProtoReflect.Descriptor instead.
func (*GetEventsWeekReq) Descriptor() ([]byte, []int) {
	return file_CalendarService_proto_rawDescGZIP(), []int{6}
}

func (x *GetEventsWeekReq) GetStart() *timestamppb.Timestamp {
	if x != nil {
		return x.Start
	}
	return nil
}

type GetEventsWeekResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*Event               `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventsWeekResp) Reset() {
	*x = GetEventsWeekResp{}
	mi := &file_CalendarService_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventsWeekResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventsWeekResp) ProtoMessage() {}

func (x *GetEventsWeekResp) ProtoReflect() protoreflect.Message {
	mi := &file_CalendarService_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventsWeekResp.ProtoReflect.Descriptor instead.
func (*GetEventsWeekResp) Descriptor() ([]byte, []int) {
	return file_CalendarService_proto_rawDescGZIP(), []int{7}
}

func (x *GetEventsWeekResp) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

type GetEventsMonthReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Start         *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventsMonthReq) Reset() {
	*x = GetEventsMonthReq{}
	mi := &file_CalendarService_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventsMonthReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventsMonthReq) ProtoMessage() {}

func (x *GetEventsMonthReq) ProtoReflect() protoreflect.Message {
	mi := &file_CalendarService_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventsMonthReq.ProtoReflect.Descriptor instead.
func (*GetEventsMonthReq) Descriptor() ([]byte, []int) {
	return file_CalendarService_proto_rawDescGZIP(), []int{8}
}

func (x *GetEventsMonthReq) GetStart() *timestamppb.Timestamp {
	if x != nil {
		return x.Start
	}
	return nil
}

type GetEventsMonthResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*Event               `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventsMonthResp) Reset() {
	*x = GetEventsMonthResp{}
	mi := &file_CalendarService_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventsMonthResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventsMonthResp) ProtoMessage() {}

func (x *GetEventsMonthResp) ProtoReflect() protoreflect.Message {
	mi := &file_CalendarService_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventsMonthResp.ProtoReflect.Descriptor instead.
func (*GetEventsMonthResp) Descriptor() ([]byte, []int) {
	return file_CalendarService_proto_rawDescGZIP(), []int{9}
}

func (x *GetEventsMonthResp) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

var File_CalendarService_proto protoreflect.FileDescriptor

const file_CalendarService_proto_rawDesc = "" +
	"\n" +
	"\x15CalendarService.proto\x12\bcalendar\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"7\n" +
	"\x0eCreateEventReq\x12%\n" +
	"\x05event\x18\x01 \x01(\v2\x0f.calendar.EventR\x05event\"\xfb\x01\n" +
	"\x05Event\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x129\n" +
	"\n" +
	"start_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12\x1f\n" +
	"\vtime_before\x18\a \x01(\x03R\n" +
	"timeBefore\"G\n" +
	"\x0eUpdateEventReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12%\n" +
	"\x05event\x18\x02 \x01(\v2\x0f.calendar.EventR\x05event\" \n" +
	"\x0eDeleteEventReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"C\n" +
	"\x0fGetEventsDayReq\x120\n" +
	"\x05start\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x05start\";\n" +
	"\x10GetEventsDayResp\x12'\n" +
	"\x06events\x18\x01 \x03(\v2\x0f.calendar.EventR\x06events\"D\n" +
	"\x10GetEventsWeekReq\x120\n" +
	"\x05start\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x05start\"<\n" +
	"\x11GetEventsWeekResp\x12'\n" +
	"\x06events\x18\x01 \x03(\v2\x0f.calendar.EventR\x06events\"E\n" +
	"\x11GetEventsMonthReq\x120\n" +
	"\x05start\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x05start\"=\n" +
	"\x12GetEventsMonthResp\x12'\n" +
	"\x06events\x18\x01 \x03(\v2\x0f.calendar.EventR\x06events2\xb7\x03\n" +
	"\bCalendar\x12A\n" +
	"\vCreateEvent\x12\x18.calendar.CreateEventReq\x1a\x16.google.protobuf.Empty\"\x00\x12A\n" +
	"\vUpdateEvent\x12\x18.calendar.UpdateEventReq\x1a\x16.google.protobuf.Empty\"\x00\x12A\n" +
	"\vDeleteEvent\x12\x18.calendar.DeleteEventReq\x1a\x16.google.protobuf.Empty\"\x00\x12G\n" +
	"\fGetEventsDay\x12\x19.calendar.GetEventsDayReq\x1a\x1a.calendar.GetEventsDayResp\"\x00\x12J\n" +
	"\rGetEventsWeek\x12\x1a.calendar.GetEventsWeekReq\x1a\x1b.calendar.GetEventsWeekResp\"\x00\x12M\n" +
	"\x0eGetEventsMonth\x12\x1b.calendar.GetEventsMonthReq\x1a\x1c.calendar.GetEventsMonthResp\"\x00B\aZ\x05./;pbb\x06proto3"

var (
	file_CalendarService_proto_rawDescOnce sync.Once
	file_CalendarService_proto_rawDescData []byte
)

func file_CalendarService_proto_rawDescGZIP() []byte {
	file_CalendarService_proto_rawDescOnce.Do(func() {
		file_CalendarService_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_CalendarService_proto_rawDesc), len(file_CalendarService_proto_rawDesc)))
	})
	return file_CalendarService_proto_rawDescData
}

var file_CalendarService_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_CalendarService_proto_goTypes = []any{
	(*CreateEventReq)(nil),        // 0: calendar.CreateEventReq
	(*Event)(nil),                 // 1: calendar.Event
	(*UpdateEventReq)(nil),        // 2: calendar.UpdateEventReq
	(*DeleteEventReq)(nil),        // 3: calendar.DeleteEventReq
	(*GetEventsDayReq)(nil),       // 4: calendar.GetEventsDayReq
	(*GetEventsDayResp)(nil),      // 5: calendar.GetEventsDayResp
	(*GetEventsWeekReq)(nil),      // 6: calendar.GetEventsWeekReq
	(*GetEventsWeekResp)(nil),     // 7: calendar.GetEventsWeekResp
	(*GetEventsMonthReq)(nil),     // 8: calendar.GetEventsMonthReq
	(*GetEventsMonthResp)(nil),    // 9: calendar.GetEventsMonthResp
	(*timestamppb.Timestamp)(nil), // 10: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 11: google.protobuf.Empty
}
var file_CalendarService_proto_depIdxs = []int32{
	1,  // 0: calendar.CreateEventReq.event:type_name -> calendar.Event
	10, // 1: calendar.Event.start_time:type_name -> google.protobuf.Timestamp
	10, // 2: calendar.Event.end_time:type_name -> google.protobuf.Timestamp
	1,  // 3: calendar.UpdateEventReq.event:type_name -> calendar.Event
	10, // 4: calendar.GetEventsDayReq.start:type_name -> google.protobuf.Timestamp
	1,  // 5: calendar.GetEventsDayResp.events:type_name -> calendar.Event
	10, // 6: calendar.GetEventsWeekReq.start:type_name -> google.protobuf.Timestamp
	1,  // 7: calendar.GetEventsWeekResp.events:type_name -> calendar.Event
	10, // 8: calendar.GetEventsMonthReq.start:type_name -> google.protobuf.Timestamp
	1,  // 9: calendar.GetEventsMonthResp.events:type_name -> calendar.Event
	0,  // 10: calendar.Calendar.CreateEvent:input_type -> calendar.CreateEventReq
	2,  // 11: calendar.Calendar.UpdateEvent:input_type -> calendar.UpdateEventReq
	3,  // 12: calendar.Calendar.DeleteEvent:input_type -> calendar.DeleteEventReq
	4,  // 13: calendar.Calendar.GetEventsDay:input_type -> calendar.GetEventsDayReq
	6,  // 14: calendar.Calendar.GetEventsWeek:input_type -> calendar.GetEventsWeekReq
	8,  // 15: calendar.Calendar.GetEventsMonth:input_type -> calendar.GetEventsMonthReq
	11, // 16: calendar.Calendar.CreateEvent:output_type -> google.protobuf.Empty
	11, // 17: calendar.Calendar.UpdateEvent:output_type -> google.protobuf.Empty
	11, // 18: calendar.Calendar.DeleteEvent:output_type -> google.protobuf.Empty
	5,  // 19: calendar.Calendar.GetEventsDay:output_type -> calendar.GetEventsDayResp
	7,  // 20: calendar.Calendar.GetEventsWeek:output_type -> calendar.GetEventsWeekResp
	9,  // 21: calendar.Calendar.GetEventsMonth:output_type -> calendar.GetEventsMonthResp
	16, // [16:22] is the sub-list for method output_type
	10, // [10:16] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_CalendarService_proto_init() }
func file_CalendarService_proto_init() {
	if File_CalendarService_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_CalendarService_proto_rawDesc), len(file_CalendarService_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_CalendarService_proto_goTypes,
		DependencyIndexes: file_CalendarService_proto_depIdxs,
		MessageInfos:      file_CalendarService_proto_msgTypes,
	}.Build()
	File_CalendarService_proto = out.File
	file_CalendarService_proto_goTypes = nil
	file_CalendarService_proto_depIdxs = nil
}
