apiVersion: apps/v1
kind: Deployment
metadata:
  name: rb-deployment
  labels:
    app: rb
    version: "1.0"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rb
  template:
    metadata:
      labels:
        app: rb
    spec:
      containers:
        - name: rb
          image: rabbitmq:latest
