[logger]
level = "debug"
mod = "console"

[storage]
mod = "sql"
dsn = "host=192.168.1.20 port=54321 user=otus_user password=otus_password dbname=otus sslmode=disable"
migration = "migrations"

[http]
host = "localhost"
port = 8080

[grpc]
host = "localhost"
port = 50051