[logger]
level = "debug"
mod = "console"

[storage]
mod = "memory"
dsn = "host=192.168.1.20 port=5432 user=otus_user password=otus_password dbname=otus sslmode=disable options='-c search_path=calendar'"
migration = "migrations"

[http]
host = "localhost"
port = 8080

[grpc]
host = "localhost"
port = 50051