[logger]
mod = "console"
path = "scheduler.log"
level = "debug"

[rabbitmq]
uri = "amqp://guest:guest@192.168.1.20:5672/"
exchange = "events"
exchange_type = "topic"
queue = "events-queue"
binding_key = "event.#"
consumer_tag = "events-consumer"